//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Sequrity_Que { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
